### ISSUE TITLE
Missing `isCancelled` argument in `onAnimationFinish` callback

### ISSUE THREAD

**Issue by reichhartd** [margelo/react-native-skottie#14]
The current implementation of the `onAnimationFinish` callback lacks the `isCancelled` argument, which is a feature in [lottie-react-native](https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md). This argument allows for distinguishing between animations that finish naturally and those interrupted by user actions or app processes.

**Comment by hannojg** [comment]
`onAnimationFinish` with `isCancelled` has been added in version `2.1.0` 😊
