### ISSUE TITLE
Minimum react-native version ?

### ISSUE THREAD

**Issue by ranaavneet** [margelo/react-native-skottie#15]
Hey guys, thanks for this awesome library. I wanted to try it out but facing a problem in installing this with various errors on iOS and Android.

Upon googling, most of the errors seems to be hinting towards the fact that I am on RN@0.70.14 and this library probably requires a higher minimum version.

Is that correct?

**Comment by hannojg** [comment]
Feel free to share the build errors you are getting. Its probably a mix of things 😅 
The example app is on RN Version 0.72.X, so 0.72 should definitely work!

**Comment by ranaavneet** [comment]
I get the following error on RN@0.70.14

`A problem occurred configuring project ':react-native-skottie'.
> Could not resolve all files for configuration ':react-native-skottie:classpath'.
   > Could not find com.android.tools.build:gradle:.
     Required by:
         project :react-native-skottie
   > Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by:
         project :react-native-skottie`

**Comment by ranaavneet** [comment]
Hi @hannojg! could you guide me to fix this issue ?

**Comment by GandalftheGuide** [comment]
> I get the following error on RN@0.70.14
> 
> ` A problem occurred configuring project ':react-native-skottie'.
> 
> > Could not resolve all files for configuration ':react-native-skottie:classpath'.
> > Could not find com.android.tools.build:gradle:.
> > Required by:
> > project :react-native-skottie
> > Could not find com.facebook.react:react-native-gradle-plugin:.
> > Required by:
> > project :react-native-skottie
> > `
> 
> _All the other libraries work fine, even skia works fine. Note: My skia version is **`0.1.230`**_ and i am on `**oldArch**`

I am in the same exact situation @ranaavneet.  Same error message, my react native version is 0.70.7

**Comment by hannojg** [comment]
The library supports only RN >= 0.71.x, which is now also set in the `package.json` peerDependency configuration.
It's possible to add support for RN 0.70.0
However, supporting more older versions adds more maintenance overhead, and we don't have the resources to support older versions.
So, either you need to upgrade to use rn-skottie, or feel free to add RN 0.70 support.
For that all that needs to be done is to update the build scripts I think!
