### ISSUE TITLE
Can not build iOS after installing the package

### ISSUE THREAD

**Issue by nurikjohn** [margelo/react-native-skottie#16]
<img width="429" alt="image" src="https://github.com/margelo/react-native-skottie/assets/54258406/6adc7067-5d70-4d02-a9b0-b497cd3b15e8">

Platform: iOS
@shopify/react-native-skia: 0.1.231

**Comment by Arron-Gill** [comment]
Same issue here - RN 0.73

**Comment by hannojg** [comment]
Thank you for creating an issue! I am looking actively into this issue

**Comment by hannojg** [comment]
Hey, can you please retest with version 2.0.2 ?

**Comment by nurikjohn** [comment]
@hannojg thanks for quick response.

pod install failed

![image](https://github.com/margelo/react-native-skottie/assets/54258406/468ab7fc-ade1-424b-a830-1515243ea379)


```
"react-native": "0.72.1"
"@shopify/react-native-skia": "^0.1.231"
```

**Comment by hannojg** [comment]
Can you try removing all node_modules and installing them again? What package manager do you use?

**Comment by hannojg** [comment]
Oh yeah I can reproduce the issue with `yarn`, while installing with `npm` seems to work. Give me a moment …

**Comment by hannojg** [comment]
Can you please retest with version 2.0.3? Thanks

**Comment by nurikjohn** [comment]
@hannojg 2.0.3 is working, thanks a lot.

**Comment by nurikjohn** [comment]
@hannojg Setting loop={false} is not affecting the animation, it is looping regardless of that.

**Comment by hannojg** [comment]
Okay, can you put that in a separate ticket with a full code example pls? Closing this one as fixed

**Comment by Arron-Gill** [comment]
Thanks for the fix! Super quick
