### ISSUE TITLE
IOS build issue

### ISSUE THREAD

**Issue by relaxxpls** [margelo/react-native-skottie#17]
Platform iOS
Cloned main on commit `3850942410b9e9d4fcbfc3ca2a8ad601198ec0f4`
and got the error

```
repo/node_modules/react-native-skottie/cpp/JsiSkSkottie.h:11:10 'modules/skottie/include/Skottie.h' file not found
```

**Comment by hannojg** [comment]
Hey, can you please retest with the latest version? I think it should be fixed. Thanks

**Comment by relaxxpls** [comment]
Update: Upon using quotes instead of Angle bracket, it builds succesfully. But upon running the application and using Skottie, I get a non-std C++ exception

![image](https://github.com/margelo/react-native-skottie/assets/63250453/4498ff8a-d09e-4112-af0a-a9922038a8c0)

**Comment by hannojg** [comment]
Question, why do you install from the git repo and not by installing the package. The packages artifact on npm actually contains stuff that's not present in the repo.

**Comment by relaxxpls** [comment]
I had initially installed from the git repo, cause the changes had not been released and I was too eager to give it a try. Later, I installed from the repo.
Now, upon clearing my xcode cache and rebuilding, all errors have vanished.
I really appreciate your quick responses and fixes!
