### ISSUE TITLE
Dotlotties not loading on iOS

### ISSUE THREAD

**Issue by relaxxpls** [margelo/react-native-skottie#18]
The library works great with lottie files, but I am unable to load a dotlottie file on iOS

```
      <Skottie
        autoPlay
        loop={false}
        source={'../assets/lotties/coins.lottie'}
        style={styles.splash}
        resizeMode="cover"
        onAnimationFinish={closeSplash}
      />
```

Version: 2.0.3

**Comment by hannojg** [comment]
Is there any error you are getting? There is support for .lottie files build in

**Comment by relaxxpls** [comment]
No error in my console, ill try providing a snack to reproduce.

**Comment by hannojg** [comment]
Closed in favour of 
- https://github.com/margelo/react-native-skottie/issues/40 

which is more detailed. Will look into it soon
