### ISSUE TITLE
onAnimationFinish is not invoked

### ISSUE THREAD

**Issue by relaxxpls** [margelo/react-native-skottie#19]
onAnimationFinish isn't called for my lottie animation on iOS. I have tested without loop (and with aswell).
I am unsure about Android.

**Comment by relaxxpls** [comment]
Is it pending implementation?

https://github.com/margelo/react-native-skottie/blob/3850942410b9e9d4fcbfc3ca2a8ad601198ec0f4/package/src/SkottieView.tsx#L170

**Comment by relaxxpls** [comment]
@hannojg could you help?

**Comment by hannojg** [comment]
`onAnimationFinish` has been added in version `2.1.0` 😊

**Comment by relaxxpls** [comment]
@hannojg Epic, testing rn!
