### ISSUE TITLE
[BUG] Tried to register two views with the same name SkiaPictureView

### ISSUE THREAD

**Issue by daehyeonmun2021** [margelo/react-native-skottie#20]
![CleanShot 2024-01-25 at 22 13 24@2x](https://github.com/margelo/react-native-skottie/assets/96194917/e97d2c12-2122-4a85-8016-17235416aaed)

Hello, I love Skottie. Thanks for introducing amazing lib :)

I found out when I use useFont and skottie together, my app crashed.
I guess there are some issues using them together.

Here is the code below.

```
import { useFont } from '@shopify/react-native-skia';
import { FC } from 'react';
import { Skottie } from 'react-native-skottie';

export const Example: FC = () => {
  const font = useFont(require('.Hind-Bold.ttf'));
  
  return (
    <Skottie
      source={require('./lottie.json')}
      style={{ width: '100%', height: '100%' }}
      autoPlay
      loop
    />
  );
};
```

Thanks :)

**Comment by hannojg** [comment]
Thanks for the reproduction will take a look at that soon!

**Comment by JuanRdBO** [comment]
I actually have the same bug

**Comment by hannojg** [comment]
Hm, can you guys please create a full reproduction? I can't reproduce it:

![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-28 at 11 17 37](https://github.com/margelo/react-native-skottie/assets/16821682/952ee8d0-a070-4f28-9fe5-8226b0f8a320)

```tsx
import {Canvas, Text, useFont, Fill} from '@shopify/react-native-skia';
import React, {type FC} from 'react';
import {View} from 'react-native';
import {Skottie} from 'react-native-skottie';

const Example: FC = () => {
  const font = useFont(require('./sable.ttf'));
  const fontSize = 32;

  return (
    <View style={{flex: 1}}>
      <Skottie
        source={require('./Fireworks.json')}
        style={{flex: 1}}
        autoPlay
        loop
      />
      <Canvas style={{flex: 1}}>
        <Fill color="white" />
        <Text x={0} y={fontSize} text="Hello World" font={font} />
      </Canvas>
    </View>
  );
};

export default Example;
```

**Comment by hannojg** [comment]
I mean like a full code example as zip or uploaded to Github, that would be perfect, thanks

**Comment by diwash007** [comment]
I had encountered same problem. The problem is that you have 2 versions of React Native Skia installed. Please check your lock files and install only one version of React Native Skia.
