### ISSUE TITLE
Feature request: Play a section of the animation

### ISSUE THREAD

**Issue by eljubec** [margelo/react-native-skottie#23]
It would be great if Skottie's `play` method would accept start and end frame parameters, similar to Lottie's approach. 
For reference: [Lottie React Native - Methods (Imperative API)](https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md#methods-imperative-api).

**Comment by hannojg** [comment]
Good idea, same as #13 thus closing this one 😊
