### ISSUE TITLE
'RNSkiaModule.h' file not found with <angled> include; use "quotes" instead 

### ISSUE THREAD

**Issue by mmr94** [margelo/react-native-skottie#25]
simple patch for ios native module

**Comment by JimTeva** [comment]
Same problem with version 2.1.0. This is strange because user @relaxxxpls encounters the same problem [here](https://github.com/margelo/react-native-skottie/issues/17#issuecomment-1910033570) but seems to get it work by installing the latest version...

**Comment by hannojg** [comment]
Can anyone of you please provide a reproduction repository for that issue? Much appreciated, thanks! 😊

**Comment by JimTeva** [comment]
[Here](https://github.com/JimTeva/testSkia2) you are.

**Comment by idrakimuhamad** [comment]
I'm having this too in latest version. Downgraded to 2.0.4, also still have it. With Skia 0.1.230 and 0.1.237.

**Comment by JimTeva** [comment]
@hannojg any luck with the repo I provided?

**Comment by hannojg** [comment]
Hey, just checked your reproduction. The issue seems to arise due to the usage of `use_frameworks`. 
Will check if we can get that fixed 😊

**Comment by JimTeva** [comment]
`use_frameworks` is now mandatory if we want to use Firebase, so I need that. Thanks @hannojg

**Comment by idrakimuhamad** [comment]
I also use Firebase, so use_framework is needed unfortunately.

**Comment by JimTeva** [comment]
@hannojg  is there any fix for use_frameworks?

**Comment by roy-sandoval** [comment]
I'm having the same issue and also use Firebase

**Comment by exzos28** [comment]
@hannojg I've tried to fix it, but it looks like a linking problem because Firebase requires linkage static. Do you think we can use angled symbols for both situations?

**Comment by hannojg** [comment]
Is using angle brackets fixing the issue for you? When I tested it fixed this particular build error but then caused a bunch of others. 

Is using react-native-skia with Firebase / use_frameworks possible?

**Comment by idrakimuhamad** [comment]
https://github.com/Shopify/react-native-skia/issues/652#issuecomment-1280278930

Can anyone try this?

**Comment by JimTeva** [comment]
@hannojg Yes the workaround that @idrakimuhamad mentionned is the one that allows to install skia without errors. The podfile I gave you already includes this workaround

**Comment by idrakimuhamad** [comment]
Yeah i think we don't actually need the workaround as it's already being part of the pod-spec now(?)

https://github.com/Shopify/react-native-skia/pull/1400

**Comment by JimTeva** [comment]
@idrakimuhamad I've tried without it and it doesn't work but maybe I did something wrong. Please make a new project and install react native skia and if it works then provide a repository for us thanks

**Comment by thoth-seshat** [comment]
I'm also running into this same issue:
Running expo:
```
"@shopify/react-native-skia": "0.1.241",
"expo": "50.0.8",
"react-native-skottie": "^2.1.0",
...
```

I'll have to fall back to `react-native-lottie` until I can upgrade to skottie when this is resolved. If anyone is working on it, LMK if you need anymore info. I don't have bandwidth to attempt to find the issue at the moment but can't help test or give feedback. 


<img width="1086" alt="Screenshot 2024-03-04 at 10 49 14 PM" src="https://github.com/margelo/react-native-skottie/assets/122938275/ef2eaffa-3c3b-4610-a301-244fc5d40b32">

**Comment by themtaysw** [comment]
![Screenshot 2024-03-11 at 22 15 23](https://github.com/margelo/react-native-skottie/assets/84338336/cd3cc605-756a-4e0a-9563-112e3acfd1e6)
 xdddd

**Comment by themtaysw** [comment]
i mean... this error is here for a good moment now, did they abandon the project or what xdd

**Comment by JimTeva** [comment]
@hannojg 🥺

**Comment by ejkkan** [comment]
Also seeing this. Would be great with a fix asap!

**Comment by amrathhugo** [comment]
Can someone help with any workaround for this issue for now?
Thanks

**Comment by kadiraydinli** [comment]
Is there any progress on this issue?

**Comment by JimTeva** [comment]
Thank you very much @hannojg

**Comment by JimTeva** [comment]
> Should be fixed in version https://github.com/margelo/react-native-skottie/releases/tag/v2.1.1
Thank you
I've tried but unfortunately still the same for me, maybe that's just me...
@idrakimuhamad have you tried?
I'll try to provide a repo for @hannojg

**Comment by idrakimuhamad** [comment]
Thanks. I'm able to build the app as of v2.1.1, though I'm getting some other crashes related to my lottie file. I will open another ticket.

**Comment by JimTeva** [comment]
Thank you very much @hannojg (building ok with React-native@0.72.6 + @shopify/react-native-skia@1.2.3 and react-native-skottie@2.1.4 - I mentionned this because updating skia was very important also)
