### ISSUE TITLE
Progress controlled crashes example app

### ISSUE THREAD

**Issue by gabimoncha** [margelo/react-native-skottie#30]
Reproducing repo: `example app` 

Instructions: Enabling **Progress controlled** switch and opening any animation crashes the app.

**Simulator screenshot**
<img width="300" alt="Simulator screenshot" src="https://github.com/margelo/react-native-skottie/assets/39256258/f0c9362c-76c5-42c3-95e1-9b423e8e5f38">

**Xcode screenshot**
<img width="1393" alt="Xcode Screenshot" src="https://github.com/margelo/react-native-skottie/assets/39256258/ebc8c2bd-9785-4f8f-aec3-da792f2354af">

**Comment by hannojg** [comment]
Thanks for the report!
