### ISSUE TITLE
Missing file `JniSkiaBaseView.h`

### ISSUE THREAD

**Issue by nazzamp** [margelo/react-native-skottie#31]
I got the error:  "`JniSkiaBaseView.h` file not found" when building android app (Android Studio Iguana). Seem like this file is missing in `package/android/cpp/jni/include`

**Comment by kierancrown** [comment]
Also experiancing this issue

**Comment by tamacroft** [comment]
same here, is this lib still maintainable ?

**Comment by hannojg** [comment]
It is, I just hadn't had the time yet to look into it.
Any PRs are appreciated 🙏

**Comment by nobodyguy** [comment]
This lib is only compatible with old Skia versions.
Try to install @shopify/react-native-skia@0.1.230

**Comment by hannojg** [comment]
Yes this should work now, let me know if it doesn't!
